name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build
        run: gulp

      - name: Deploy
        uses: FirebaseExtended/action-hosting-deploy@v1
        with:
          firebase_version: '9.23.0'
          token: ${{ secrets.FIREBASE_TOKEN }}
          project_id: ${{ secrets.FIREBASE_PROJECT_ID }}
          site_id: ${{ secrets.FIREBASE_SITE_ID }}
          public_dir: ./dist